specVersion: 1.0.0
name: cronos-crow-token-transfers-via-rpc
version: 0.0.1
runner:
  node:
    name: "@subql/node-cosmos"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  A basic Ethermint EVM example project with an event and call handler via the Ethermint RPC API. Read
  more about this at https://academy.subquery.network/build/cosmos-evm.html.
  This project can be use as a starting point for developing your SubQuery
  project
repository: >-
  https://github.com/subquery/cosmos-subql-starter/tree/main/Cronos/cronos-evm-starter
schema:
  file: ./schema.graphql
network:
  chainId: cronosmainnet_25-1
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # Take a look here for some Cronos endpoints https://moonflow.solutions/rpc-servers
  endpoint: "https://rpc.cronos.org/"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  #dictionary: "https://api.subquery.network/sq/subquery/cosmos-cronos-dictionary"
  chainTypes:
    ethermint.evm.v1:
      file: ./proto/ethermint/evm/v1/tx.proto
      messages:
        - MsgEthereumTx
        - LegacyTx
        - AccessListTx
        - DynamicFeeTx
    ethermint.evm.v12:
      file: ./proto/ethermint/evm/v1/evm.proto
      messages:
        - AccessTuple
    google.protobuf:
      file: ./proto/google/protobuf/any.proto
      messages:
        - Any
dataSources:
  - kind: cosmos/EthermintEvm
    startBlock: 4750000 #1752764 
    processor:
      file: ./node_modules/@subql/ethermint-evm-processor/dist/bundle.js
      options:
        abi: erc721 #change the option here
        address: "0x9676c33E31e43731B03E71D42385F7f677D7929d"  #"0xc843f18d5605654391e7eDBEa250f6838C3e8936" 
    assets:
      erc721:
        file: ./cro-crow.abi.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: cosmos/EthermintEvmEvent
          filter:
            topics:
              - "Transfer(address indexed from, address indexed to, uint256 indexed tokenId)"
              - null
              - null
              - null
